# Generated by Django 4.2.16 on 2024-12-05 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeceasedEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(default='', max_length=100)),
                ('last_modified_by', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('chart_num', models.CharField(default='', max_length=15)),
                ('dob', models.DateField(default=datetime.datetime(2024, 12, 5, 15, 36, 22, 796998))),
                ('state_where_died', models.CharField(default='', max_length=15)),
                ('death_cert_num', models.CharField(default='', max_length=20)),
                ('dod', models.DateField(default=datetime.datetime(2024, 12, 5, 15, 36, 22, 796998))),
                ('place_of_death', models.CharField(default='', max_length=50)),
                ('race', models.CharField(default='', max_length=20)),
                ('autopsy_performed', models.BooleanField(default=False)),
                ('manner_of_death', models.CharField(default='', max_length=30)),
                ('death_by_work_injury', models.BooleanField(default=False)),
                ('place_of_injury', models.CharField(default='', max_length=50)),
                ('method_of_verification', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ICDCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DeceasedCodes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deathrr.icdcode')),
                ('deceased_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deathrr.deceasedentry')),
            ],
        ),
    ]
