# Generated by Django 4.2.16 on 2024-12-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deathrr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceasedentry',
            name='chart_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedentry',
            name='death_cert_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedentry',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedentry',
            name='dod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedentry',
            name='manner_of_death',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedentry',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedentry',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedentry',
            name='place_of_injury',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedentry',
            name='race',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedentry',
            name='state_where_died',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
