# Generated by Django 4.2.16 on 2024-12-10 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deathrr', '0002_alter_deceasedentry_chart_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceasedentry',
            name='dod',
            field=models.DateField(default=datetime.date(2024, 12, 10)),
        ),
    ]
