# Generated by Django 4.2.16 on 2024-12-10 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deathrr', '0003_alter_deceasedentry_dod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceasedentry',
            name='dod',
            field=models.DateField(default=datetime.datetime(2024, 12, 10, 15, 29, 30, 695187, tzinfo=datetime.timezone.utc)),
        ),
    ]
