# Generated by Django 4.2.16 on 2024-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deathrr', '0004_alter_deceasedentry_dod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceasedentry',
            name='dod',
            field=models.DateField(),
        ),
    ]
