# Generated by Django 4.2.16 on 2025-01-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deathrr', '0005_alter_deceasedentry_dod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceasedentry',
            name='state_where_died',
            field=models.CharField(blank=True, default='North Carolina', max_length=15, null=True),
        ),
    ]
