# Generated by Django 4.2.16 on 2025-01-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deathrr', '0006_alter_deceasedentry_state_where_died'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceasedentry',
            name='race',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
