# Generated by Django 4.2.16 on 2025-01-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deathrr', '0008_remove_deceasedentry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceasedentry',
            name='created_by',
            field=models.CharField(blank=True, default='jill.sain@cherokeehospital.org', max_length=100, null=True),
        ),
    ]
