# Generated by Django 4.2.16 on 2025-01-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deathrr', '0010_alter_deceasedentry_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceasedentry',
            name='deleted_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
