# Generated by Django 4.2.16 on 2025-01-22 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deathrr', '0011_alter_deceasedentry_deleted_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceasedentry',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date(2030, 1, 1), null=True),
        ),
    ]
