# Generated by Django 4.2.16 on 2025-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deathrr', '0013_icdcode_ien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icdcode',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
