# Generated by Django 5.0 on 2025-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deathrr', '0014_alter_icdcode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icdcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
